---
title: "Hakkımda / About me"
output: html_document
---

<html>
<head>
<style>
hr { 
  display: block;
  margin-top: 0.5em;
  margin-bottom: 0.5em;
  margin-left: auto;
  margin-right: auto;
  border-style: inset;
  border-width: 1px;
} 
</style>
</head>
<body>

<br />

<div style="text-align: justify"> Dil, ister konuşmak ister işaretleşmek yoluyla, insan iletişimin en eski sistemlerinden biri olarak karşımıza çıkıyor. Dünyanın büyük çoğunluğu birden fazla dil biliyor ve bu dilleri gündelik hayatında etkin bir biçimde kullanıyor, bu da bize "çok dilli" olmanın sanılanın aksine "tek dilli" olmaktan çok daha olağan bir durum olduğunu gösteriyor.

Çok dilli olmak yarattığı sonuçlar açısından psikoloji, sosyoloji ve dilbilim gibi bilim dalları için çok önemli ve ilginç bir olgu. Kullandığımız dillerin birbirleriyle sürekli bir etkileşim halinde olduğu artık bilim çevrelerince kabul görmüş durumda. İşte bu etkileşimin çok dilli kişilerin dil temsillerini ve dil kullanımını nasıl etkileyebileceği, bu etkinin hangi psikolojik mekanizmalar ve toplumsal etmenlerle ilişkili olabileceği benim araştırma alanlarımı oluşturuyor. Bu konuları araştırırken psikodilbilimin ve sosyodilbilimin yöntemlerini kullanıyorum, ve yakın gelecekte bilişimsel yöntemlerden de faydalanmayı planlıyorum.

Araştırmalarım hakkında konuşmak isterseniz benimle sağ üstte bulunan kanallar aracılığıyla iletişime geçebilirsiniz. </div>

<br />
<hr>
<br />

<div style="text-align: justify"> I am interested in how the languages we speak interact with each other, and how this interaction may change our representation of these languages. My research concerns the intersection of bilingualism, cross-language interactions, and language change. I study these issues using psycholinguistic methods and, hopefully soon, computational methods.

In case you want to talk about my research, please reach me via the channels at top right. </div>