---
title: "Publications"
---

<br />

<h3><a href="https://psyarxiv.com/2uxej/">Role of structural priming in contact-induced change: Subject pronoun expression in L1 Turkish by Turkish-Dutch bilinguals</a></h3>
<h4>Hande Sodacı, Ad Backus, Gerrit Jan Kootstra</h4>
<h6 style="text-align: right">PsyArXiv Preprints, February 14, 2019</h6>
<br />

<p style="text-align: justify">Subject pronoun expression has been extensively studied for effects of language contact, but it is fairly recent that these studies started including cross-language structural priming paradigms. The earlier studies on subject pronoun use in Turkish spoken by Turkish-Dutch bilinguals did not find any difference from monolingual speakers of Turkish but reported a few instances of unconventional use of subject pronouns, indicating the influence of Dutch on Turkish. This study aimed to determine whether structural priming may have a part in the unconventional variation observed in subject pronoun use in Turkish that is in contact with Dutch.</div>